name: release

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macos-latest]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          mkdir build/
          pushd build/
          if [ "$RUNNER_OS" = "macOS" ]; then
            g++-11 --version
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-11 ..
          else
            cmake -DCMAKE_BUILD_TYPE=Release ..
          fi
          cmake --build .
          popd
          mv build/pcse .
          mv pcse "pcse-$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')-x64"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            pcse*
